### ISSUE TITLE
[BUG] Rerunning Accuracy Score in DGA notebook eventually throws error

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/clx#437]
**Describe the bug**
Subsequent rerunning of the accuracy score cell in the Inference section returns a TypeError 
```
TypeError                                 Traceback (most recent call last)
<ipython-input-20-0c7766158fd1> in <module>
     19 print(type(pred_results[0]))
     20 print(type(true_results[0]))
---> 21 accuracy_score = accuracy_score(pred_results, true_results)
     22 
     23 print('Model accuracy: %s'%(accuracy_score))
TypeError: 'numpy.float64' object is not callable
```
**Steps/Code to reproduce bug**
1. go to https://github.com/rapidsai/clx/blob/branch-21.08/notebooks/dga_detection/DGA_Detection.ipynb
2. run the notebooks
3. repeatedly rerun the Accuracy Score Cell and it eventually happens.

**Expected behavior**
The accuracy score would be shown and no errors are through

Proposed solution by @BartleyR and @beckernick is to change the variable name as it could overwrite the function of the same name.

**Comment by BartleyR** [comment]
@efajardo-nv It looks like this is being thrown because the result of the function `accuracy_score()` is being assigned to a variable that's the same name. Looks like a fix is to replace that line with something like:

`accuracy_score_result = accuracy_score(pred_results, true_results)`

Let's test though to make sure that's the right fix.
