### ISSUE TITLE
clx: CUDA 12 Conda Packages

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/clx#526]
Pushing for CUDA 12 Conda package builds of libraries for RAPIDS 23.04. This issue is for tracking that work.

Requirements (please recheck):

```[tasklist]
### Developer tasks
- [x] I've confirmed the list below is correct (or updated if not)
```

```[tasklist]
### Toolkit dependencies from Conda
- [ ] `cuda-cudart`
- [ ] `cuda-nvcc`
- [ ] `libcublas`
- [ ] `libcufft`
- [ ] `libcurand`
- [ ] `libcusolver`
- [ ] `cuda-nvml-dev`
```

```[tasklist]
### RAPIDS Conda dependencies
- [ ] `rmm`
- [ ] `cudf`
- [ ] `cuml`
- [ ] `nvtabular` (soonish?)
```

```[tasklist]
### Other dependencies from Conda using CUDA
```

**Comment by mdemoret-nv** [comment]
@jakirkham  Dont have maintainer access here to update your comment, but here is the updated list of dependencies:

Requirements (please recheck):

```[tasklist]
### Developer tasks
- [x] I've confirmed the list below is correct (or updated if not)
```

```[tasklist]
### Toolkit dependencies from Conda
- [ ] `cuda-cudart-dev`
- [ ] `libcublas-dev`
- [ ] `libcufft-dev`
- [ ] `libcurand-dev`
- [ ] `libcusolver-dev`
- [ ] `cuda-nvml-dev`
```

```[tasklist]
### Other dependencies from Conda using CUDA
- [ ] `nvcc_linux-64`(used to build our conda packages with CMake. Could switch over to using `cuda-nvcc_linux-64` if it has the correct CMake support)
```

Couple of other notes:
- We have direct dependencies on `rmm`, `cudf`, and `cuml` so we will need whatever runtime dependencies are required by these libraries
   - We will be adding a dependency on `nvtabular` in the near future
- The `libcublas`, `libcufft`, `libcurand` and `libcusolver` dependencies are needed due to MatX. If MatX provided a conda package, we wouldnt need these dependencies directly
- I've assumed `cuda-cudart-dev`, and `cuda-compiler` are needed to support basic compilation.
   - Which packages are required was tested with [this PR](https://github.com/nv-morpheus/Morpheus/pull/627), but since our CI image has the CUDA toolkit already installed, the compiler and runtime were found outside of conda.
   - If needed, I can do some local testing to confirm this.

**Comment by jakirkham** [comment]
Thanks Michael! 🙏

I've updated the lists above

Added a RAPIDS list. Do we know when `nvtabular` will be a dependency? Will this be part of 23.04 or later?

Listed `cuda-nvcc` for compiler. Though how that exactly is added may change. Also `cuda-cudart-dev` will be a dependency of `cuda-nvcc`, but listing it out is good

Left the `-dev` off names as these are just outputs of recipes, who top-level name lacks the `-dev`. So went for the more general recipe name

Please let me know if you have more thoughts on any of this

**Comment by mdemoret-nv** [comment]
> Do we know when nvtabular will be a dependency?

Most likely in the next release or 2. We are currently investigating replacing some code with NVTabular. That work would require `nvtabular` as a dependency. I'm just not sure if we will get it into this release or if it will be the next release.

> Listed cuda-nvcc for compiler.

This makes sense. I forgot that conda-build will use the package name `cuda-nvcc_{platform}` during the build process.

Everything else looks good.

**Comment by jakirkham** [comment]
Closing and creating a new issue on Morpheus ( https://github.com/nv-morpheus/Morpheus/issues/723 )
